### PR TITLE
Arguments

### PR DESCRIPTION
**Pull request by daverumph**
Here is my set of updates to arguments.py, along with a pretty comprehensive test case in test_models.py.  Is it your style to break the tests out more?  I didn't know, and didn't do it.

--Dave

### CODE REVIEW

**Comment by shkw0k** [comment]
I wouldn't add too many features to Arguments.
It is meant to be a container for things. The framework doesn't have to know what these things are.

**Comment by daverumph** [comment]
Inside the KPF pipeline I need to be able to get at the contents in order to do some of the conditional processing we need to do.  But I can do that with either version, so feel free to reject my pull request if you prefer.  All I need is len(), append() and indexing of the positional args.

**Comment by daverumph** [comment]
Thanks!  I'll update from master.

**Comment by shkw0k** [comment]
Oops. I just pushed to master.

**Comment by daverumph** [comment]
Oops!  Well, it should be backwards compatible.  That's what the tests are to guarantee.

**Pull request merged**
