### PR TITLE
Update Requirements and Initialize Framework with Objects

### PR DESCRIPTION
**Pull request by bjfultn**
Just added Astropy, Pandas, and bokeh to the `requirements.txt` file. Was there a reason that these were excluded? If so please disregard this PR. 

Also, I suggest adding specific version numbers to the `requirements.txt` file so that updates to dependencies have no chance of breaking this package. However, there are pros and cons to this method.

### CODE REVIEW

**Comment by shkw0k** [comment]
May be bokeh should not be a requirement.  There are still some kcwi dependencies that need to be cleaned up.

**Comment by bjfultn** [comment]
OK, feel free to close this PR and deal with the dependencies as you see fit.

**Comment by bjfultn** [comment]
Also added the ability to initialize framework with `Base_pipeline` and `ConfigClass` objects instead of strings.

What is the testing procedure?

**Comment by bjfultn** [comment]
I believe that this has been implemented and this PR is no longer applicable.

**Pull request closed without merging**
