### PR TITLE
Feature/exception testing

### PR DESCRIPTION
**Pull request by daverumph**
See my issue #47 Automated testing of pipeline exceptions.

### CODE REVIEW

**Comment by shkw0k** [comment]
I may add another way to support error handling.

**Comment by daverumph** [comment]
What do you not like about this approach?  I thought it was straightforward and pretty non-invasive, but if you have specific issues, I can maybe help address them.  Enabling testing of exceptional conditions on the KPF pipeline is important for us, and I'd like to find a way to do it pretty soon.

**Comment by shkw0k** [comment]
I pushed your changes to develop.
I added push_hi_event to indicate pushing an event to the high priority queue. Push_event is still there for compatibility. But it will be removed later.

I think the action, which is a wrapper of a primitive, should catch the exceptions and decide what to do next by changing action.new_event. This can be done with simple decorator. Error handling is part of the pipeline. If the framework catches an exception, the pipeline failed because it did not handle that exception and the framework stops gracefully. If this is a test, then the assert statatement will check that the output is not what is expected, so the test failed. 
Note that the primitives should be tested individually. Also the framework has precondition checks to guard against unexpected inputs and post_conditions to check for output. 

I am thinking adding an user provided error_handler() function in the base pipeline, which the framework will call when is catches an exception. That gives the pipeline another chance to handle the exception.

**Comment by daverumph** [comment]
Thanks, Shui.  Please let us know when you make changes related to the pipeline error handling, so that we can track them.

**Pull request closed without merging**
